// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This flow automatically suggests product categories based on the product description and images.
 *
 * - autoCategorizeProduct - A function that handles the product categorization process.
 * - AutoCategorizeProductInput - The input type for the autoCategorizeProduct function.
 * - AutoCategorizeProductOutput - The return type for the autoCategorizeProduct function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutoCategorizeProductInputSchema = z.object({
  description: z.string().describe('The description of the product.'),
  photoDataUri: z
    .string()
    .describe(
      "A photo of the product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AutoCategorizeProductInput = z.infer<typeof AutoCategorizeProductInputSchema>;

const AutoCategorizeProductOutputSchema = z.object({
  suggestedCategories: z
    .array(z.string())
    .describe('An array of suggested product categories.'),
});
export type AutoCategorizeProductOutput = z.infer<typeof AutoCategorizeProductOutputSchema>;

export async function autoCategorizeProduct(input: AutoCategorizeProductInput): Promise<AutoCategorizeProductOutput> {
  return autoCategorizeProductFlow(input);
}

const prompt = ai.definePrompt({
  name: 'autoCategorizeProductPrompt',
  input: {schema: AutoCategorizeProductInputSchema},
  output: {schema: AutoCategorizeProductOutputSchema},
  prompt: `You are an expert in product categorization for an e-commerce platform.

  Based on the description and image of the product provided, suggest the most relevant categories for the product. Provide an array of suggested product categories.

  Description: {{{description}}}
  Photo: {{media url=photoDataUri}}
  Categories:`,
});

const autoCategorizeProductFlow = ai.defineFlow(
  {
    name: 'autoCategorizeProductFlow',
    inputSchema: AutoCategorizeProductInputSchema,
    outputSchema: AutoCategorizeProductOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
