// This is an autogenerated file from Firebase Studio.
// eslint-disable-next-line @next/next/no-img-element
const Logo = (props: React.ComponentPropsWithoutRef<'svg'>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={132}
    height={35}
    viewBox="0 0 132 35"
    {...props}
  >
    <text
      style={{
        fill: '#3b82f6',
        fontFamily: 'Montserrat-Bold, Montserrat',
        fontSize: 32,
        fontWeight: 700,
      }}
      transform="translate(0 28)"
    >
      <tspan x={0} y={0}>
        {'L'}
      </tspan>
    </text>
    <text
      style={{
        fill: '#3b82f6',
        fontFamily: 'Montserrat-Bold, Montserrat',
        fontSize: 32,
        fontWeight: 700,
      }}
      transform="translate(79 28)"
    >
      <tspan x={0} y={0}>
        {'KI'}
      </tspan>
    </text>
    <text
      style={{
        fill: '#a1a1aa',
        fontFamily: 'Montserrat-Regular, Montserrat',
        fontSize: 9,
      }}
      transform="translate(4.5 34.5)"
    >
      <tspan x={0} y={0}>
        {'UNLOCK YOUR NEIGHBORHOOD'}
      </tspan>
    </text>
    <g
      style={{
        fill: '#fcd34d',
        stroke: '#fcd34d',
        strokeWidth: 1,
      }}
    >
      <circle cx={14.5} cy={14.5} r={14.5} style={{ stroke: 'none' }} />
      <circle cx={14.5} cy={14.5} r={14} style={{ fill: 'none' }} />
    </g>
    <path
      d="M23.978 12.32a1.47 1.47 0 0 1-1.354.81H9.28a1.47 1.47 0 0 1-1.354-.81L5.5 6.787h20.913zM8.3 14.58a.52.52 0 1 0 .52.52.52.52 0 0 0-.52-.52zm11.758 0a.52.52 0 1 0 .52.52.52.52 0 0 0-.52-.52z"
      style={{
        fill: '#3b82f6',
      }}
    />
  </svg>
);
export default Logo;
